
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import DemoContractContractArtifactJson from '../target/otc_escrow-DemoContract.json' with { type: 'json' };
export const DemoContractContractArtifact = loadContractArtifact(DemoContractContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract DemoContract;
 */
export class DemoContractContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, DemoContractContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, DemoContractContract.artifact, wallet) as Promise<DemoContractContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, token_address: AztecAddressLike, token_amount: (bigint | number)) {
    return new DeployMethod<DemoContractContract>(PublicKeys.default(), wallet, DemoContractContractArtifact, DemoContractContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, token_address: AztecAddressLike, token_amount: (bigint | number)) {
    return new DeployMethod<DemoContractContract>(publicKeys, wallet, DemoContractContractArtifact, DemoContractContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof DemoContractContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<DemoContractContract['methods'][M]>
  ) {
    return new DeployMethod<DemoContractContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      DemoContractContractArtifact,
      DemoContractContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return DemoContractContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(DemoContractContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'definition'> {
      return {
        definition: {
      slot: new Fr(1n),
    }
      } as ContractStorageLayout<'definition'>;
    }
    

  public static get notes(): ContractNotes<'UintNote' | 'DefinitionNote'> {
    return {
      UintNote: {
          id: new NoteSelector(0),
        },
DefinitionNote: {
          id: new NoteSelector(1),
        }
    } as ContractNotes<'UintNote' | 'DefinitionNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor_self_owned(token_address: struct, token_amount: integer) */
    constructor_self_owned: ((token_address: AztecAddressLike, token_amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor_sender_owned(token_address: struct, token_amount: integer) */
    constructor_sender_owned: ((token_address: AztecAddressLike, token_amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_definition() */
    get_definition: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_in(_nonce: field) */
    transfer_in: ((_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_out() */
    transfer_out: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
